### ISSUE TITLE
HitRotation

### ISSUE THREAD

**Issue by loeffel-io** [Biebras/Unity-3D-Trajectory-Prediction#1]
Hey @Biebras,

thank you for your code example! 

I try to get the hit rotation instead of the HitPosition (Vector3 (point)); 
Can you please explain me what `return CalculateLinePoint(MaxTimeY());` is doing? 

```c#
private Vector3 HitPosition()
{
    var lowestTimeValue = MaxTimeY() / _resolutionLinecast;

    for (var i = 0; i < _resolutionLinecast + 1; i++)
    {
        var t = lowestTimeValue * i;
        var tt = lowestTimeValue * (i + 1);

        if (Physics.Linecast(CalculateLinePoint(t), CalculateLinePoint(tt), out var rayHit, _layer))
        {
            return rayHit.point;
        }
    }

    return CalculateLinePoint(MaxTimeY());
}
``` 

Would love to do something like: 

```c#
private Quaternion? HitRotation()
{
    var lowestTimeValue = MaxTimeY() / _resolutionLinecast;

    for (var i = 0; i < _resolutionLinecast + 1; i++)
    {
        var t = lowestTimeValue * i;
        var tt = lowestTimeValue * (i + 1);

        if (Physics.Linecast(CalculateLinePoint(t), CalculateLinePoint(tt), out var rayHit, _layer))
        {
            return rayHit.transform.rotation;
        }
    }

    return null;
}
``` 

Thank you for your help!

**Comment by loeffel-io** [comment]
Even better would be something like:

```c#
private RaycastHit? RaycastHit()
{
    var lowestTimeValue = MaxTimeY() / _resolutionLinecast;

    for (var i = 0; i < _resolutionLinecast + 1; i++)
    {
        var t = lowestTimeValue * i;
        var tt = lowestTimeValue * (i + 1);

        if (Physics.Linecast(CalculateLinePoint(t), CalculateLinePoint(tt), out var rayHit, _layer))
        {
            return rayHit;
        }
    }

    return null; // CalculateLinePoint(MaxTimeY());
}
```

That works really great, but i have no glue what `CalculateLinePoint(MaxTimeY());` is for

**Comment by Biebras** [comment]
Unfortunately to you, I wrote this code a long time ago, however, I'm 95% sure that this function returns: how long it takes a ball to land in respect of Y coordinate. About your code could you explain more what you are trying to do, I might be able to help you.

Have a great coding day!

**Comment by loeffel-io** [comment]
Hey @Biebras, thank you for your response! 

I think (not sure) this function just returns the point (Vector3) of the collision game object. 
For example: You throw a ball and this function return the explicit point where the ball will land on the ground. 
I want to use the codebase to get the final raycastHit where the ball is landing (i dont need any line drawing etc).
I use this function for this and that works pretty good, but i can't understand what the last line `CalculateLinePoint(MaxTimeY());` is about 

Do you understand what i mean? Can give you any information you need 

Edit: Have a great coding day too! :smiling_face_with_three_hearts:

**Comment by Biebras** [comment]
Alright,
The MaxTimeY returns time it takes to reach the Y limit. Furthermore, I return CalculateLinePoint(MaxTimeY()); when the ball doesn't collide with anything.

**Comment by loeffel-io** [comment]
Ok great, so it makes sense to just `return null`?

**Comment by Biebras** [comment]
Yeah

**Comment by loeffel-io** [comment]
Perfect, thank you!
